FROM frolvlad/alpine-oraclejdk8:slim
#FROM openjdk:8
VOLUME /tmp
COPY target/SpringBootMySQLRabbitDocker-0.0.1-SNAPSHOT.jar SpringBootMySQLRabbitDocker.jar
ENTRYPOINT ["java","-jar","/SpringBootMySQLRabbitDocker.jar"]
